# Assignment
## Programming for Data Analysis
### numpy.random package
#### *Eibhinn Lee*


https://www.markdownguide.org/basic-syntax/

---

In [7]:
import numpy as np

#### Task 1 
***
Overall purpose of the package
---

#### Task 2
***
1. Simple Random Package
2. Permutations

Permutations

a. shuffle
b. permutations

Shuffle

In [9]:
# Example 1
rng = np.random.default_rng()
arr = np.arange(10)
rng.shuffle(arr)
arr

array([5, 9, 2, 4, 3, 8, 6, 1, 7, 0])

In [10]:
# Example 2
arr = np.arange(9).reshape((3, 3))
rng.shuffle(arr, axis=1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Permutations

In [11]:
# Example 1

rng = np.random.default_rng()
rng.permutation(15)

array([ 7, 13,  0,  1,  9,  6,  2,  5, 14, 10,  3, 12, 11,  4,  8])

In [12]:
# Example 2

rng.permutation([1025, 56, 4, 17, 100])

array([ 100,   56,    4, 1025,   17])

#### Task 3

#### Task 4