# Assignment
## Programming for Data Analysis
### numpy.random package
#### *Eibhinn Lee*


https://www.markdownguide.org/basic-syntax/

---

In [3]:
import numpy as np

#### Task 1 
***

Overall purpose of the package
---

Definition
***
This module is part of the numpy library. Basically, it contains functions that are used to randomly generate numbers. Within the module contains some simple random data generation methods, some permutation and distribution functions, and random generator functions. https://www.javatpoint.com/numpy-random

#### Task 2
***
1. Simple Random Package
2. Permutations
---

*Simple Random Data*

Random function = Outputs return between (0.0,1.0)




https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random

https://www.javatpoint.com/numpy-random



In [4]:
#Example 1

# np.random.rand = used to generate random numbers 
# in the below example the '3' refers to the rows of output and 
#the '5' refers to the number of random numbers randomly gererated

a = np.random.rand(3, 5)

# Returns 3 rows each containing 5 randomly generated numbers between 0.0 -> 1.0

a

array([[0.47636248, 0.64688877, 0.16048122, 0.40855055, 0.0203252 ],
       [0.29569751, 0.10171801, 0.80510145, 0.39150296, 0.30681722],
       [0.43971463, 0.87869463, 0.67384226, 0.89784202, 0.50094312]])

In [5]:
# Example 2

# Randomly generating a single number
# Re-run to show the randomly generated number each time

c = np.random.random()
# Returns random number between 0.0 -> 1.0
c

0.28584237043330707

In [6]:
#integers

rng = np.random.default_rng()
rng.integers(3, size=10)


array([2, 0, 1, 0, 0, 2, 1, 1, 0, 2], dtype=int64)

In [7]:
#bytes

qq = np.random.bytes(7)
qq

b'5\xc9\x16)\x89\xd1]'

*Permutations*

##### a. shuffle
##### b. permutations

A.Shuffle

In [8]:
# random shuffle
tt = np.arange(12)
np.random.shuffle(tt)
tt

array([ 5,  2,  8,  1,  9,  3,  4, 11,  0,  7,  6, 10])

In [ ]:
# Choice example 1
a=np.random.choice(5,3)  
a

In [9]:
# NON-Integers
aa_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
rng.choice(aa_arr, 5, p=[0.5, 0.1, 0.1, 0.3])


array(['Christopher', 'Christopher', 'Christopher', 'pooh', 'Christopher'],
      dtype='<U11')

In [ ]:
B.Permutations

In [10]:
# Example 1

rng = np.random.default_rng()
rng.permutation(15)

array([ 5,  3,  7,  9, 13,  2, 10,  1, 11, 14, 12,  0,  8,  6,  4])

In [11]:
# Example 2

rng.permutation([1025, 56, 4, 17, 100])

array([   4,   17,   56,  100, 1025])

#### Task 3

Five Distributions with the numpy.random package
---

#### Task 4